env:
    node: true
    es6: true
extends: [airbnb-base, "plugin:prettier/recommended"]
plugins: []
parserOptions:
    sourceType: module
    allowImportExportEverywhere: false
    parser: optionalChaining
    codeFrame: false

# 0 = Desativa a Regra, 1 = Ativa a regra como um aviso, 2 = Ativa a regra como um erro

rules:
    arrow-body-style: [2, as-needed]
    arrow-spacing: 2
    complexity: [2, 50]
    max-depth: [2, 4]
    max-params: [2, 3]
    max-statements: [2, 25]
    max-nested-callbacks: [2, 4]
    max-len: [1, code: 200]
    no-unused-vars: 2
    no-alert: 2
    no-caller: 2
    no-console: 1
    no-empty-function: 2
    no-else-return: 2
    no-extend-native: 2
    no-new-wrappers: 2
    no-script-url: 2
    no-throw-literal: 2
    no-void: 2
    no-with: 2
    no-trailing-spaces: 2
    no-duplicate-imports: 2
    no-useless-constructor: 2
    no-var: 2
    no-eval: 2
    no-undef: 2
    no-new-object: 0
    prefer-promise-reject-errors: 2
    prefer-rest-params: 2
    quotes: [2, double]
    require-await: 2
    semi: [2, always]
    linebreak-style: 0
    no-plusplus: 0
